<a href="https://colab.research.google.com/github/harinme/ai/blob/main/6%EB%84%8C%ED%8C%8C%EC%9D%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy # 넌파이 설치

In [22]:
import numpy as np # 넌파이 import
a=np.array(0) # 스칼라
print(a)
print(a.ndim)
type(a)
print('')

a2= np.array([1,2,3,4]) # 벡터
print(a2)
print(a2.ndim)
type(a2)
print('')

a3=np.array([[1,2,3],[4,5,6,],[7,8,9]]) # 행렬 3행 3열
print(a3)
print(a3.ndim)
type(a3)
print('')

a4=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]]) # 텐서 2면 3행 2열
print(a4)
print(a4.ndim)
print(a4.shape)
type(a4)
print('')

# 3면 2행 2열
a5=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(a5)
print(a5.ndim)
print(a5.shape)
type(a5)



0
0

[1 2 3 4]
1

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
(2, 3, 2)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
3
(3, 2, 2)


numpy.ndarray

In [34]:
# reshaping
b= np.arange(12) # 1차원 벡터를 생성
print(b)
print('')

b.shape
b.shape= 2,-1
print(b)
print('')

b.shape= 3,-1
print(b)
print('')

b.shape=-1,1
print(b)
print('')

b.shape=-1,3
print(b)
print('')

b.shape=-1
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [36]:
# reshaping
b= np.arange(12) # 1차원 벡터를 생성
print(b)
print('')

b.shape
b.shape= 2,-1
print(b)
print(b.size, '~~~~')
print('')

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
12 ~~~~



- 자료형
  - int형(정수)
    - int64, int16, int8, uint64
    - -2^63 ~ 2^63 -1 범위의 정수를 표현할 수 있다.
    - -2^15 ~ 2^15 -1
    - 0 ~ 2^127 unit64의 정수 표현의 범위 양의정수만 구한다.

  - float형(실수) - 부동소숫점 표현방식(자료 검색 할 때)
    - float64- 소숫점 15까지 정확하다, float32 - 6, float16 -2
    - 자료 저장 모습: 부호 비트 1비트   지부수(7비트)  가수부(8 or 24 or 58)
    - 소숫점 아래를 저장하는 공간이 많아지게 하는 것
    - 실수의 기본은 float64이다.

  - complex형(복소수)
    - complex128, complex64

In [45]:
#int32의 자료표현의 범위 -2147483648 ~ 2147483647까지 정수 표현의 범위
a= np.array([1,3,5,7,9], np.int32) # 8비트 -2^7 ~ +2^7 -1 = -128 ~ 127까지 정수 표현할 수 있다.
print(a)
a.dtype
print('')

a1=np.array([2147483646,2147483647,2147483649], np.int32)
print(a1)
print('')

a2= np.array([2**63,2**63+1,2**63+2])
print(a2)
a2.dtype
print('')

a3= np.array([2**62-2**63])
print(a3)
a3.dtype
print('')

a4= np.array([1,3,5,7,9]) #64비트로 처리
print(a4)
a4.dtype

# 결론 자료형을 명시하지 않으면 정수형의 기본은 int64이다.
# 너무 큰 자료형이므로 메모리 절약을 위해서 int8, int16, int32로 바꿀 수 있다.


[1 3 5 7 9]

[ 2147483646  2147483647 -2147483647]

[9223372036854775808 9223372036854775809 9223372036854775810]

[-4611686018427387904]

[1 3 5 7 9]


<ipython-input-45-ef31f5270f80>:7: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 2147483649 to int32 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  a1=np.array([2147483646,2147483647,2147483649], np.int32)


dtype('int64')

In [48]:
# 실수형
a= np.array(3.141592653589793, np.float64)
print(a)
a.dtype

3.141592653589793


dtype('float64')

In [51]:
a= np.array([1,2j,3+4j,2.72+3.14j])
print(a)
a.dtype
a.real # 실수만 추출
a.imag # 허수만 추출
print(a.real.dtype, '!!')
print(a.imag.dtype,'~~')

[1.  +0.j   0.  +2.j   3.  +4.j   2.72+3.14j]
float64 !!
float64 ~~


1. 인덱싱 indexing
  1) 1DArray
  2) 2DArray

2. 슬라이싱 slicing
  1) 1DArray
  2) 2DArray
  
3. interating
  1) 1DArray
  2) 2DArray

In [54]:
# 인덱싱 indexing 1) 1DArray 2) 2DArray
a=np.array([1,3,5,7,9])
print(a)
print(a.ndim)
print(a.shape)
print(a[0])
print(a[3])
print(a[4])

[1 3 5 7 9]
1
(5,)
1
7
9


In [66]:
# 인덱싱 indexing 1) 1DArray 2) 2DArray
a2=np.array([[1,3,5],[2,4,6]])
print(a2)
print(a2.ndim)
print(a2.shape)
# 1 5 4 추출
print(a2[0,0],a2[0,2], a2[1,1])
print(a2[0,2], a2[1,1])

# 6, 3
print( a2[1,2], a2[0,1])
# 3값을 13을 바꾸기
a2[0,1] = 13
# 2값을 25로 바꾸기
a2[1,0] = 25
print( a2 )

# 0번 행 전체의 값에다 +10을 한다면
print(a2[0])
print(a2[0,: ])
print(a2[0,0:3])
a2[0]=a2[0]+10
print(a2[0])

# 1번 행에 2를 전부 곱하기
a2[1]= a2[1]*2
a2[1] *= 2
# 1번열에 2를 전부 나누기
a2[:,1:2] = a2[:,:1:2]/2



[[1 3 5]
 [2 4 6]]
2
(2, 3)
1 5 4
5 4
6 3
[[ 1 13  5]
 [25  4  6]]
[ 1 13  5]
[ 1 13  5]
[ 1 13  5]
[11 23 15]


In [86]:
a3=np.arange(15)
print(a3[1:10:2])
print(a3[2:12:2])
print(a3[-1:9:-1])
print(a3[::])
print(a3[1:2])
print(a3[-1])

[1 3 5 7 9]
[ 2  4  6  8 10]
[14 13 12 11 10]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[1]
14


In [87]:
b= np.arange(10,22).reshape(3,4)
for bb in b:
  print(bb)

[10 11 12 13]
[14 15 16 17]
[18 19 20 21]


In [88]:
# arange
a=np.arange(10,101,5)
print(a)
a=np.arange(10,dtype=np.float32)
print(a)

# 0. 0.1 0.2 ... 0.9
a=np.arange(0.0, 1.0, 0.1, dtype=np.float32)
a=np.arange(0, 1,0.1)
print(a)
print(a.dtype)

[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
float64


In [89]:
# reshape
a=np.array([1,2,3,4,5,6]).reshape(2,3)
print(a)

[[1 2 3]
 [4 5 6]]


In [90]:
# r_ row 행
a=np.array([1,2,3])
b=np.array([4,5,6,7])
print(a)
print(b)
c=np.r_[a,b]
print(c)

[1 2 3]
[4 5 6 7]
[1 2 3 4 5 6 7]


In [91]:
# c_column 열 형태로 합치기
a= np.array([1,2,3])
b=np.array([4,5,6])
print(a)
print(b)
c=np.c_[a,b]
print(c)

[1 2 3]
[4 5 6]
[[1 4]
 [2 5]
 [3 6]]


In [92]:
# hstack-수평, vstack-수직
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.hstack((a,b)) # (튜플){딕셔너리}[리스트]
print(c)


[[1 2 5 6]
 [3 4 7 8]]


In [94]:
# empty 항목을 초기화하지 않고 주어진 모양과 유형의 새 배열을 반환
a=np.empty(4)
print(a)
a=np.empty(4, dtype=np.int64)
print(a)
a=np.empty((2,4), dtype= np.int32)
print(a)

[4.9e-324 9.9e-324 1.5e-323 2.0e-323]
[1 2 3 4]
[[1 0 2 0]
 [3 0 4 0]]


### Math Operation

In [100]:
# 행렬 곱하기
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[2,2],[3,3],[4,4]])
c=a@b
print(c)
np.matmul(a,b)
print(c)

[[20 20]
 [47 47]]
[[20 20]
 [47 47]]


In [104]:
# 제곱
a=np.array([1,2,3,4])
a1=np.square(a) #제곱
print(a1)

# 제곱그
a=np.array(1,2,3,4,)



[ 1  4  9 16]


TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [106]:
from numpy import pi,e

In [107]:
print(pi)
print(e)

3.141592653589793
2.718281828459045


In [111]:
import numpy as np
np.exp(1)
x= np.array([0,1,2])
y=np.exp(x)
print(y)

[1.         2.71828183 7.3890561 ]


In [113]:
import matplotlib.pyplot as plt # 지수 함수로 그래프 그림
x=np.linespace(-2,2,100)
y=np.exp(x)
print(y)



AttributeError: module 'numpy' has no attribute 'linespace'

In [ ]:
# 0~99까지 10행 10열 2차원 배열 만들기
a=np.arang

### 가
# 가
## 가
#

우수 초콜릿 분석하기

In [117]:
import numpy as np
from google.colab import files
files.upload()
data=np.loadtxt('chocolate_rating.csv', delimiter=',')


Saving chocolate_rating.csv to chocolate_rating (2).csv


In [119]:
# print(data)
print(data.ndim)
print(data.shape)
print(data.size)


2
(1795, 4)
7180


In [133]:
rating=data[:,3].mean()
print(rating)

high_level=data[data[:,3]>=4]
print(high_level[0:10])
high_id=high_level[:,0].astype(np.int64)
print(high_id)
print('우수 초코릿 수는?', high_id.size

)

3.185933147632312
[[1.000e+01 2.014e+03 7.000e-01 4.000e+00]
 [1.800e+01 2.013e+03 7.000e-01 4.000e+00]
 [2.100e+01 2.013e+03 6.300e-01 4.000e+00]
 [5.500e+01 2.011e+03 7.000e-01 4.000e+00]
 [5.700e+01 2.010e+03 7.000e-01 4.000e+00]
 [7.700e+01 2.007e+03 7.000e-01 4.000e+00]
 [7.800e+01 2.007e+03 7.500e-01 4.000e+00]
 [7.900e+01 2.007e+03 7.000e-01 5.000e+00]
 [8.400e+01 2.007e+03 7.000e-01 4.000e+00]
 [8.700e+01 2.006e+03 7.000e-01 5.000e+00]]
[  10   18   21   55   57   77   78   79   84   87   88   93  108  109
  118  124  153  180  181  187  223  232  233  240  243  244  245  248
  257  312  316  317  358  437  503  567  573  574  582  601  650  687
  690  691  701  720  730  800  828  862  864  865  866  883  919  993
 1088 1089 1118 1119 1120 1204 1241 1245 1247 1274 1277 1278 1289 1291
 1293 1295 1323 1331 1336 1378 1394 1426 1428 1433 1479 1488 1513 1516
 1529 1530 1531 1533 1536 1537 1544 1545 1664 1683 1686 1688 1694 1700
 1740 1757]
우수 초코릿 수는? 100


In [136]:
high_kakao= high_level[:,2]
print(high_kakao)
unique_values, value_counts=np.unique(high_kakao, return_counts=True)
print('카카오 함유량', unique_values)
print('함유량 별 빈도수', value_counts)

[0.7  0.7  0.63 0.7  0.7  0.7  0.75 0.7  0.7  0.7  0.66 0.6  0.7  0.7
 0.7  0.72 0.7  0.73 0.72 0.72 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75
 0.7  0.71 0.7  0.7  0.72 0.75 0.7  0.7  0.7  0.7  0.7  0.7  0.68 0.7
 0.74 0.69 0.7  0.74 0.7  0.72 0.7  0.74 0.7  0.72 0.72 0.7  0.7  0.63
 0.68 0.74 0.67 0.65 0.64 0.75 0.7  0.7  0.7  0.75 0.7  0.67 0.7  0.72
 0.72 0.72 0.75 0.75 0.8  0.75 0.75 0.7  0.78 0.65 0.7  0.72 0.7  0.75
 0.88 0.7  0.67 0.7  0.7  0.7  0.64 0.7  0.7  0.63 0.69 0.64 0.64 0.7
 0.7  0.7 ]
카카오 함유량 [0.6  0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7  0.71 0.72 0.73 0.74 0.75
 0.78 0.8  0.88]
함유량 별 빈도수 [ 1  3  4  2  1  3  2  2 45  1 11  1  4 17  1  1  1]


In [142]:
max_idx=np.argmax(value_counts)
print(max_idx)
print(unique_values[max_idx])
print('우수초콜릿', high_id.size, '가지 중', value_counts[max_idx], '가지의 카카오 함유량이', unique_values[max_idx]*100, '% 입니다')

8
0.7
우수초콜릿 100 가지 중 45 가지의 카카오 함유량이 70.0 % 입니다
